name: Post Next Meeting
run-name: ${{ github.actor }} is setting the link to the next meeting
on: [push]
jobs:
  post-next-meeting:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install icalendar

      - name: Run Python script
        run: python scripts/post-next-meeting.py