name: Post Next Meeting
run-name: ${{ github.actor }} is setting the link to the next meeting
on:
  schedule:
    # Run at 8:05 PM CST every Thursday
    - cron: "5 20 * * 4"
  workflow_dispatch:

permissions:
  contents: read

jobs:
  post-next-meeting:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install icalendar
          python -m pip install requests

      - name: Run Python script
        run: python scripts/post-next-meeting.py

      - name: Commit and push changes
        run: |
          date > generated.txt
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "generated"
          git push      
